# Generated by Django 4.0.4 on 2022-05-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_usernotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevi',
            name='dificulty',
            field=models.TextField(default='begginer'),
        ),
        migrations.AddField(
            model_name='coursevi',
            name='instructor',
            field=models.TextField(default='instructor 1'),
        ),
        migrations.AddField(
            model_name='coursevi',
            name='price',
            field=models.TextField(default='free'),
        ),
        migrations.AddField(
            model_name='coursevi',
            name='testing',
            field=models.BooleanField(default=False),
        ),
    ]
